mytuple = ('Blue','Black','Orange','Red','Green','Yellow')
print(mytuple)

print(mytuple[0:5])
print(mytuple[5:6])
print(mytuple[2:85])
print(mytuple[1:])
print(mytuple[:6])
print(mytuple[:])
print(mytuple[:-1])
print(mytuple[-5:])
print(mytuple[-2:-6])
print(mytuple[1:0])
print(mytuple[1:1])
print(mytuple[-5:5])
print(mytuple[1:-1])
print(mytuple[0:6:2])
print(mytuple[::-1])